vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /fichier
            upload_destination: '%kernel.project_dir%/public/fichier'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
